import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { getStatus, outputUrl, uploadVideo } from './api'
import { Activity, ArrowDownToLine, ArrowRight, Camera, Check, CircleAlert, CircleDot, FileImage, FileVideo, History, Info, LayoutDashboard, Menu, Plus, Settings, Upload, X } from 'lucide-react'

const OrbitScene = lazy(() => import('./components/three/OrbitScene'))
const fadeRise = { initial: { opacity: 0, y: 14 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.45, ease: 'easeOut' } }

const MAX_SIZE = 500 * 1024 * 1024
const MODEL_NAME = 'best_phone_bag_hard_negative_yolo11s.pt'
const time = (seconds = 0) => `${Math.floor(seconds / 60)}:${String(Math.round(seconds % 60)).padStart(2, '0')}`
const bytes = (value) => `${(value / 1048576).toFixed(1)} MB`
const eta = (seconds) => seconds == null ? 'calculating' : seconds < 60 ? `${Math.ceil(seconds)}s` : `${Math.floor(seconds / 60)}m ${Math.ceil(seconds % 60)}s`

function Sidebar({ active, onNavigate, onNew }) {
  const items = [['dashboard', 'Dashboard', LayoutDashboard], ['image', 'Image Detection', FileImage], ['video', 'Video Detection', FileVideo], ['camera', 'Live Camera', Camera], ['history', 'Detection History', History], ['analytics', 'Analytics', Activity], ['settings', 'Settings', Settings], ['about', 'Responsible Use', Info]]
  return <aside className="sidebar"><div className="brand"><div className="brand-mark">PW</div><div><strong>PERIMETER</strong><span>WATCH / AI MONITOR</span></div></div><div className="side-status"><i /> SYSTEM ONLINE</div><nav aria-label="Main navigation">{items.map(([id, label, Icon]) => <button key={id} className={active === id ? 'active' : ''} onClick={() => onNavigate(id)}><span className="nav-icon"><Icon size={16} strokeWidth={1.8} /></span>{label}</button>)}</nav><button className="side-action" onClick={onNew}><Plus size={16} /> New analysis</button><div className="sidebar-foot"><small>ACADEMIC PROTOTYPE</small><span>Human review required</span></div></aside>
}

function Topbar({ active, onMenu }) { return <header className="topbar"><button className="mobile-menu" onClick={onMenu} aria-label="Open navigation"><Menu size={21} /></button><div><p className="top-kicker">OPERATIONS / {active.replace('-', ' ')}</p><h1>Public Safety Vision Console</h1></div><div className="top-actions"><span className="connection"><i /> API CONNECTED</span><motion.button whileTap={{ scale: 0.94 }} className="avatar" aria-label="Operator profile">OP</motion.button></div></header> }
function MetricCard({ label, value, meta, tone = '' }) { return <motion.article {...fadeRise} whileTap={{ scale: 0.985 }} className={`metric-card ${tone} ${tone === 'alert' && Number(value) > 0 ? 'alert-active' : ''}`}><span>{label}</span><strong>{value}</strong><small>{meta}</small></motion.article> }
function EmptyState({ title, detail, action, onClick }) { return <div className="empty-state"><span><CircleDot size={28} /></span><strong>{title}</strong><p>{detail}</p>{action && <button className="button-secondary" onClick={onClick}>{action}</button>}</div> }
function HistoryRow({ item }) { return <div className="history-row"><span className={`activity-icon ${item.alerts ? 'alert' : 'normal'}`}>{item.alerts ? <CircleAlert size={14} /> : <Check size={14} />}</span><div><strong>{item.name}</strong><small>{item.type} · {new Date(item.createdAt).toLocaleString()}</small></div><b>{item.alerts ? `${item.alerts} alert${item.alerts > 1 ? 's' : ''}` : 'Normal'}</b></div> }

function Dashboard({ history, onNavigate, onNew }) {
  const totals = history.reduce((acc, item) => ({ files: acc.files + 1, people: acc.people + item.people, normal: acc.normal + item.normal, alerts: acc.alerts + item.alerts }), { files: 0, people: 0, normal: 0, alerts: 0 })
  return <motion.div {...fadeRise} className="page dashboard-page"><section className="hero-panel"><div className="hero-copy"><p className="eyebrow cyan">VISION OPERATIONS / 01</p><h2>Analyze <em>CCTV footage.</em></h2><p>Review computer-vision detections from one calm, auditable workspace. Every potential alert remains a human-review signal.</p><div className="hero-actions"><motion.button whileTap={{ scale: 0.96 }} className="button-primary" onClick={() => onNavigate('video')}>Start detection <span><ArrowRight size={16} /></span></motion.button></div></div><Suspense fallback={<div className="orbit-fallback" aria-hidden="true"><span>PW</span></div>}><OrbitScene /></Suspense><div className="hero-readout"><span>ACTIVE NODE</span><strong>PW-LOCAL-01</strong><small>Last check · just now</small></div></section><div className="section-title"><div><p className="eyebrow">LIVE OVERVIEW</p><h3>System pulse</h3></div><span className="review-note"><i /> Human review workflow</span></div><section className="metrics-grid"><MetricCard label="Processed files" value={totals.files || 'Not available'} meta="local session history" /><MetricCard label="People tracked" value={totals.people || 'Not available'} meta="unique IDs from results" tone="cyan" /><MetricCard label="Normal persons" value={totals.normal || 'Not available'} meta="class 0 detections" tone="green" /><MetricCard label="Potential alerts" value={totals.alerts || 'Not available'} meta="class 1 event windows" tone="alert" /></section><section className="dashboard-grid"><article className="panel model-card"><div className="panel-heading"><div><p className="eyebrow">ACTIVE MODEL</p><h3>YOLO11s detector</h3></div><span className="pill green">READY</span></div><div className="model-line"><span>Weights</span><strong>{MODEL_NAME}</strong></div><div className="model-line"><span>Classes</span><strong>2 / person context</strong></div><div className="model-line"><span>Device</span><strong>Reported by backend at startup</strong></div></article><article className="panel activity-card"><div className="panel-heading"><div><p className="eyebrow">RECENT ACTIVITY</p><h3>Detection history</h3></div><motion.button whileTap={{ scale: 0.95 }} className="text-button" onClick={() => onNavigate('history')}>View all <ArrowRight size={16} /></motion.button></div>{history.length ? history.slice(0, 4).map((item) => <HistoryRow key={item.id} item={item} />) : <EmptyState title="No analyses yet" detail="Upload a video to create your first local result." action="Start detection" onClick={onNew} />}</article></section></motion.div>
}

function Dropzone({ accept, onFile, file, error }) {
  const input = useRef(); const [dragging, setDragging] = useState(false)
  return <><div className={`dropzone ${dragging ? 'dragging' : ''} ${file ? 'selected' : ''}`} onClick={() => input.current?.click()} onDragOver={(event) => { event.preventDefault(); setDragging(true) }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); onFile(event.dataTransfer.files[0]) }}><input ref={input} type="file" accept={accept} onChange={(event) => onFile(event.target.files[0])} /><span className="drop-glyph"><Upload size={36} /></span><strong>{file ? file.name : 'Drop footage here'}</strong><small>{file ? bytes(file.size) : 'or click to browse · MP4 / MOV / AVI / MKV / WEBM'}</small></div>{error && <p className="inline-error">{error}</p>}</>
}

function Processing({ jobId, onDone, onError }) {
  const [status, setStatus] = useState({ progress: 0, current_frame: 0, total_frames: 0, processing_fps: null, eta_seconds: null })
  useEffect(() => { let active = true; const poll = async () => { try { const result = await getStatus(jobId); if (!active) return; setStatus(result); if (result.status === 'done') onDone(result); if (result.status === 'error') onError(result.error) } catch (error) { if (active) onError(error.message) } }; poll(); const interval = setInterval(poll, 1000); return () => { active = false; clearInterval(interval) } }, [jobId, onDone, onError])
  return <section className="processing-card panel"><div className="processing-orbit"><span>PW</span></div><p className="eyebrow cyan">MODEL INFERENCE IN PROGRESS</p><h2>Reading the <em>perimeter.</em></h2><div className="progress-header"><span>FRAME ANALYSIS</span><strong>{status.progress}%</strong></div><div className="progress-track"><i style={{ width: `${status.progress}%` }} /></div><strong className="frame-count">Processing frame {status.current_frame.toLocaleString()} / {status.total_frames ? status.total_frames.toLocaleString() : '...'}</strong><div className="telemetry"><span>{status.processing_fps ? `${status.processing_fps.toFixed(1)} frames/sec` : 'Starting inference'}</span><span>ETA {eta(status.eta_seconds)}</span><span>BYTETRACK ACTIVE</span></div><p className="muted-copy">The annotated video will appear automatically when the frame stream is complete.</p></section>
}

function VideoWorkspace({ onJob, activeResult, onResult }) {
  const [file, setFile] = useState(null); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false)
  const choose = (candidate) => { if (!candidate) return; if (candidate.size > MAX_SIZE) return setError('Video exceeds the 500MB limit.'); if (!candidate.type.startsWith('video/') && !/\.(mp4|mov|avi|mkv|webm)$/i.test(candidate.name)) return setError('Choose an MP4, MOV, AVI, MKV, or WEBM file.'); setError(''); setFile(candidate) }
  const submit = async () => { if (!file || submitting) return; setSubmitting(true); setError(''); try { onJob(await uploadVideo(file)); setSubmitting(false) } catch (err) { setError(err.message); setSubmitting(false) } }
  if (activeResult) return <ResultView data={activeResult} onReset={() => onResult(null)} />
  return <div className="page detection-page"><div className="page-intro"><div><p className="eyebrow cyan">VIDEO DETECTION / 02</p><h2>Review footage<br /><em>with context.</em></h2><p>Track people across the full clip and inspect potential alert windows. Results are review signals, not conclusions.</p></div><div className="workflow-stepper"><span className="done">01 Upload</span><i /><span className="current">02 Analyze</span><i /><span>03 Review</span></div></div><section className="upload-layout"><article className="panel upload-card"><div className="panel-heading"><div><p className="eyebrow">SOURCE FOOTAGE</p><h3>Upload a video</h3></div><span className="pill">MAX 500 MB</span></div><Dropzone accept=".mp4,.mov,.avi,.mkv,.webm,video/*" onFile={choose} file={file} error={error} /><div className="upload-meta"><span>Supported: MP4, MOV, AVI, MKV, WEBM</span><span>Local processing</span></div><button className="button-primary full" disabled={!file || submitting} onClick={submit}>{submitting ? 'Uploading...' : 'Analyze footage'} <span><ArrowRight size={16} /></span></button></article><aside className="panel protocol-card"><p className="eyebrow">ANALYSIS PROTOCOL</p><h3>What happens next</h3><ol><li><b>01</b><span>Frames are read at source resolution and frame rate.</span></li><li><b>02</b><span>YOLO11s + ByteTrack assigns stable person IDs.</span></li><li><b>03</b><span>Green and red boxes are burned into the output video.</span></li></ol><div className="review-callout"><span>i</span><p>Potential alert means human review required. It does not identify intent or identity.</p></div></aside></section></div>
}

function ResultView({ data, onReset }) { const { summary } = data; const download = () => { const anchor = document.createElement('a'); anchor.href = outputUrl(data.output_video); anchor.download = data.output_video; anchor.click() }; const exportJson = () => { const blob = new Blob([JSON.stringify(summary, null, 2)], { type: 'application/json' }); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(blob); anchor.download = 'perimeter-watch-summary.json'; anchor.click() }; return <div className="page result-page"><div className="result-toolbar"><div><p className="eyebrow cyan">ANALYSIS COMPLETE / HUMAN REVIEW</p><h2>Annotated <em>footage.</em></h2></div><div><button className="button-secondary" onClick={exportJson}>Export JSON</button><button className="button-primary" onClick={onReset}>New analysis</button></div></div><section className="result-video panel"><video controls playsInline preload="metadata" src={outputUrl(data.output_video)} /><div className="video-caption"><span>ANNOTATED OUTPUT · H.264</span><span className="legend"><i className="green-dot" /> NORMAL <i className="red-dot" /> POTENTIAL ALERT</span><button className="text-button" onClick={download}>Download video <ArrowDownToLine size={16} /></button></div></section><section className="result-stats"><MetricCard label="Normal persons" value={summary.unique_normal_person_count} meta="unique tracked IDs" tone="green" /><MetricCard label="Potential alerts" value={summary.unique_potentially_dangerous_person_count} meta="review required" tone="alert" /><MetricCard label="Duration" value={time(summary.duration_seconds)} meta={`${summary.total_frames.toLocaleString()} frames · ${summary.fps.toFixed(1)} FPS`} /></section><section className="panel alert-log"><div className="panel-heading"><div><p className="eyebrow">EVENT LOG</p><h3>Potential alert windows</h3></div><span className="pill alert">{summary.alert_events.length} FLAGGED</span></div>{summary.alert_events.length ? summary.alert_events.map((event, index) => <div className="alert-event" key={`${event.start_seconds}-${event.end_seconds}`}><span>{String(index + 1).padStart(2, '0')}</span><strong>{time(event.start_seconds)} - {time(event.end_seconds)}</strong><small>Potential alert · human review required</small></div>) : <EmptyState title="No potential alert windows" detail="No dangerous-person event windows were returned for this clip." />}</section></div> }

function ImageDetection() { const [file, setFile] = useState(null); const [preview, setPreview] = useState(''); const choose = (candidate) => { if (!candidate?.type.startsWith('image/')) return; setFile(candidate); setPreview(URL.createObjectURL(candidate)) }; return <div className="page"><div className="page-intro compact"><div><p className="eyebrow cyan">IMAGE DETECTION / 03</p><h2>Inspect a <em>single frame.</em></h2><p>The backend currently exposes video analysis only. Preview your image here, then connect an image route when available.</p></div></div><section className="upload-layout"><article className="panel upload-card"><Dropzone accept="image/*" onFile={choose} file={file} /><button className="button-primary full" disabled={!file}>Image endpoint unavailable</button></article><article className="panel preview-card">{preview ? <img src={preview} alt="Selected inspection frame" /> : <EmptyState title="No image selected" detail="PNG, JPG, and WEBP previews will appear here." />}</article></section></div> }
function LiveCamera() { const videoRef = useRef(); const [stream, setStream] = useState(null); const [error, setError] = useState(''); const start = async () => { try { const next = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' }, audio: false }); setStream(next); if (videoRef.current) videoRef.current.srcObject = next } catch (err) { setError(`Camera permission unavailable: ${err.message}`) } }; const stop = () => { stream?.getTracks().forEach((track) => track.stop()); setStream(null) }; useEffect(() => () => stream?.getTracks().forEach((track) => track.stop()), [stream]); return <div className="page"><div className="page-intro compact"><div><p className="eyebrow cyan">LIVE CAMERA / 04</p><h2>Observe <em>responsibly.</em></h2><p>Camera preview is available with permission. Live inference requires a dedicated streaming endpoint, which is not part of the current backend.</p></div></div><section className="camera-panel panel"><div className="camera-frame">{stream ? <video ref={videoRef} autoPlay playsInline /> : <div className="camera-empty"><span><CircleDot size={42} /></span><strong>Camera is off</strong><small>No camera starts without your permission.</small></div>}</div>{error && <p className="inline-error">{error}</p>}<div className="camera-controls"><button className="button-primary" onClick={stream ? stop : start}>{stream ? 'Stop camera' : 'Start camera'}</button><span className="pill amber">LIVE DETECTION UNAVAILABLE</span></div></section></div> }
function HistoryPage({ history, onClear }) { return <div className="page"><div className="page-intro compact"><div><p className="eyebrow cyan">DETECTION HISTORY / 05</p><h2>Local <em>activity.</em></h2><p>Metadata is stored in this browser only. Original videos are not copied into history.</p></div><button className="button-secondary" disabled={!history.length} onClick={onClear}>Clear history</button></div><section className="panel table-panel">{history.length ? <div className="history-table"><div className="table-head"><span>INPUT</span><span>TYPE</span><span>PEOPLE</span><span>ALERTS</span><span>DATE</span></div>{history.map((item) => <div className="table-row" key={item.id}><strong>{item.name}</strong><span>{item.type}</span><span>{item.people}</span><span className={item.alerts ? 'text-alert' : ''}>{item.alerts}</span><span>{new Date(item.createdAt).toLocaleString()}</span></div>)}</div> : <EmptyState title="Your history is empty" detail="Completed video analyses will appear here." />}</section></div> }
function Analytics({ history }) { const totals = history.reduce((acc, item) => ({ normal: acc.normal + item.normal, alerts: acc.alerts + item.alerts }), { normal: 0, alerts: 0 }); const max = Math.max(totals.normal, totals.alerts, 1); return <div className="page"><div className="page-intro compact"><div><p className="eyebrow cyan">ANALYTICS / 06</p><h2>Signals, <em>not verdicts.</em></h2><p>Charts are calculated only from completed results stored in this browser.</p></div></div><section className="analytics-grid"><article className="panel chart-card"><div className="panel-heading"><h3>Detection balance</h3><span className="pill">{history.length} files</span></div><div className="bar-chart"><div><span>Normal</span><i><b className="bar-green" style={{ width: `${totals.normal / max * 100}%` }} /></i><strong>{totals.normal}</strong></div><div><span>Potential alerts</span><i><b className="bar-red" style={{ width: `${totals.alerts / max * 100}%` }} /></i><strong>{totals.alerts}</strong></div></div></article><article className="panel chart-card"><div className="panel-heading"><h3>Data coverage</h3></div><div className="coverage-ring"><strong>{history.length}</strong><span>completed<br />analyses</span></div><p className="muted-copy">No fabricated historical values are shown. Add more reviewed clips to make trends meaningful.</p></article></section></div> }
function SettingsPage({ settings, onChange, onReset }) { return <div className="page"><div className="page-intro compact"><div><p className="eyebrow cyan">SETTINGS / 08</p><h2>Tune the <em>review layer.</em></h2><p>These controls affect interface alerts only. They do not change model training or backend inference thresholds.</p></div><button className="button-secondary" onClick={onReset}>Reset defaults</button></div><section className="panel settings-card"><Setting label="General detection threshold" value={settings.confidence} onChange={(value) => onChange('confidence', value)} /><Setting label="Potential alert threshold" value={settings.dangerous} onChange={(value) => onChange('dangerous', value)} /><Setting label="Required consecutive alert frames" value={settings.frames} min="1" max="10" step="1" onChange={(value) => onChange('frames', value)} /><label className="toggle-row"><span>Alert sound</span><input type="checkbox" checked={settings.sound} onChange={(event) => onChange('sound', event.target.checked)} /><i /></label><label className="toggle-row"><span>Reduced motion</span><input type="checkbox" checked={settings.motion} onChange={(event) => onChange('motion', event.target.checked)} /><i /></label></section></div> }
function Setting({ label, value, onChange, min = '0.1', max = '1', step = '0.05' }) { return <label className="range-row"><span>{label}</span><output>{value}</output><input type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} /></label> }
function About() { return <div className="page narrow-page"><p className="eyebrow cyan">RESPONSIBLE USE / 09</p><h2>Built for <em>review.</em></h2><div className="panel prose-card"><p>Perimeter Watch is an academic computer-vision prototype and one module in a larger safety and security pipeline.</p><p>A potential alert is a prompt for qualified human review. The system does not identify people, infer intent, establish guilt, or confirm criminal behavior.</p><p>Keep operators in the loop, validate results against local policy, and treat model outputs as fallible signals.</p></div></div> }

export default function App() {
  const defaults = { confidence: 0.4, dangerous: 0.7, frames: 3, sound: false, motion: false }
  const [active, setActive] = useState('dashboard'); const [mobileOpen, setMobileOpen] = useState(false); const [jobId, setJobId] = useState(''); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [history, setHistory] = useState(() => JSON.parse(localStorage.getItem('perimeter-history') || '[]')); const [settings, setSettings] = useState(() => ({ ...defaults, ...JSON.parse(localStorage.getItem('perimeter-settings') || '{}') }))
  useEffect(() => localStorage.setItem('perimeter-history', JSON.stringify(history)), [history]); useEffect(() => localStorage.setItem('perimeter-settings', JSON.stringify(settings)), [settings])
  const navigate = (next) => { setActive(next); setMobileOpen(false); setError('') }; const start = (upload) => { setJobId(upload.job_id); setResult(null); setActive('video'); setError('') }; const fail = useCallback((message) => { setError(message || 'Processing failed.'); setJobId('') }, []); const finish = useCallback((data) => { setResult(data); setJobId(''); setHistory((items) => [{ id: crypto.randomUUID(), name: data.output_video || 'processed video', type: 'Video', people: (data.summary?.unique_normal_person_count || 0) + (data.summary?.unique_potentially_dangerous_person_count || 0), normal: data.summary?.unique_normal_person_count || 0, alerts: data.summary?.alert_events?.length || 0, createdAt: new Date().toISOString() }, ...items]) }, []); const content = jobId ? <Processing jobId={jobId} onDone={finish} onError={fail} /> : active === 'dashboard' ? <Dashboard history={history} onNavigate={navigate} onNew={() => navigate('video')} /> : active === 'video' ? <VideoWorkspace onJob={start} activeResult={result} onResult={setResult} /> : active === 'image' ? <ImageDetection /> : active === 'camera' ? <LiveCamera /> : active === 'history' ? <HistoryPage history={history} onClear={() => { if (window.confirm('Clear local detection history?')) setHistory([]) }} /> : active === 'analytics' ? <Analytics history={history} />  : active === 'settings' ? <SettingsPage settings={settings} onChange={(key, value) => setSettings((current) => ({ ...current, [key]: value }))} onReset={() => setSettings(defaults)} /> : <About />
  return <div className={`app ${settings.motion ? 'force-reduced-motion' : ''}`}><Sidebar active={active} onNavigate={navigate} onNew={() => navigate('video')} /><div className={`app-main ${mobileOpen ? 'mobile-open' : ''}`}><Topbar active={active} onMenu={() => setMobileOpen((open) => !open)} />{error && <div className="toast error-toast" role="alert">{error}<button onClick={() => setError('')}><X size={16} /></button></div>}<AnimatePresence mode="wait"><motion.div key={jobId ? 'processing' : active} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.22 }}>{content}</motion.div></AnimatePresence><footer><span>PERIMETER WATCH · YOLO11s / BYTETRACK</span><span>HUMAN REVIEW REQUIRED · LOCAL NODE ONLINE</span></footer></div></div>
}





